- name: import key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present

- name: add Debian repo
  when: ansible_distribution == "Debian"
  apt_repository:
    repo: "{{ mongodb_repo_debian }}"
    state: present
    update_cache: true

- name: add Ubuntu repo
  when: ansible_distribution == "Ubuntu"
  apt_repository:
    repo: "{{ mongodb_repo_ubuntu }}"
    state: present
    update_cache: true

- name: install package
  apt:
    name: mongodb-org
    state: present
