- name: import key
  apt_key:
    url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present

- when: ansible_distribution == "Debian"
  set_fact:
    mongodb_repo: "{{ mongodb_repo_debian }}"

- when: ansible_distribution == "Ubuntu"
  set_fact:
    mongodb_repo: "{{ mongodb_repo_ubuntu }}"

- name: add repo
  apt_repository:
    repo: "{{ mongodb_repo }}"
    state: present
    update_cache: true

- name: install package
  apt:
    name: mongodb-org
    state: present
