- hosts: servers
  remote_user: ansible
  become: true

  vars:
    certbot_email: "{{ admin_email }}"
    matrix_synapse_domain: "{{ chat_matrix_domain }}"
    matrix_synapse_max_upload_size: "{{ chat_upload_size }}"
    element_domain: "{{ chat_domain }}"
    element_server_name: "{{ chat_title }}"
    element_matrix_domain: "{{ matrix_synapse_domain }}"
    element_brand: "{{ chat_title }}"
    element_welcome_user: "@{{ chat_welcome_user }}:{{ chat_matrix_domain }}"

  roles:
    - name: openssl
      when: env == "production"
      vars:
        openssl_generate_dhparam: true

    - name: ufw
      vars:
        ufw_allow_ports: ["80", "443"] # HTTP, HTTPS

    - name: certbot
      when: env == "production"
      vars:
        certbot_domain: "{{ matrix_synapse_domain }}"

    - name: certbot
      when: env == "production"
      vars:
        certbot_domain: "{{ element_domain }}"

    - name: matrix-synapse
    - name: element

    - name: nginx
      vars:
        nginx_create_reverse_proxy: true
        nginx_reverse_proxy_location: /_matrix
        nginx_reverse_proxy_url: http://localhost:8008
        nginx_reverse_proxy_body_size: 1024M
        nginx_domain: "{{ matrix_synapse_domain }}"
        ## If you want to use federation, uncomment:
        # nginx_site_additional_config: >
        #   server {
        #     listen 8448 ssl default_server;
        #     listen [::]:8448 ssl default_server;
        #     server_name mustardamus.com;
        #     location / {
        #       proxy_pass http://localhost:8008;
        #       proxy_set_header X-Forwarded-For $remote_addr;
        #     }
        #   }

    - name: nginx
      vars:
        nginx_create_static_site: true
        nginx_domain: "{{ element_domain }}"
        nginx_static_site_path: "{{ element_path }}"
