- name: import key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release | lower }} main
    state: present
    update_cache: true

- name: install package
  apt:
    name: nodejs
    state: present
