- name: install package
  apt:
    name: certbot
    state: present

- service_facts:
  register: certbot_services

- set_fact:
    certbot_services: "{{ certbot_services.ansible_facts.services }}"
    certbot_cert_path: "/etc/letsencrypt/live/{{ certbot_domain }}"

- name: stop Nginx if it is running
  when: >
    certbot_services.nginx is defined and
    certbot_services.nginx.state == "running"
  service:
    name: nginx
    state: stopped

- name: obtain certificate
  args:
    creates: "{{ certbot_cert_path }}"
  command: >
    certbot certonly \
    --standalone --noninteractive --agree-tos \
    --email {{ certbot_email }} -d {{ certbot_domain }}

- name: start Nginx if it was running
  when: >
    certbot_services.nginx is defined and
    certbot_services.nginx.state == "running"
  service:
    name: nginx
    state: restarted

- name: add cron job for certificate renewal
  cron:
    name: certbot renew
    job: certbot renew --quiet --no-self-upgrade
    hour: "{{ certbot_cron_hour }}"
    minute: "{{ certbot_cron_minute }}"
