- name: download archive
  get_url:
    url: "https://github.com/vector-im/riot-web/releases/download/v{{ riot_version }}/riot-v{{ riot_version }}.tar.gz"
    dest: /tmp/riot.tar.gz

# TODO check key

- name: extract archive
  unarchive:
    src: /tmp/riot.tar.gz
    dest: /tmp
    remote_src: true

- name: remove previous version
  file:
    path: "{{ riot_path }}"
    state: absent

- name: move to destination
  command: "mv /tmp/riot-v{{ riot_version }} {{ riot_path }}"

- name: copy config file
  template:
    src: config.json.j2
    dest: "{{ riot_path }}/config.json"
