- name: copy service file
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"

- name: enable service
  when: service_enabled
  service:
    name: "{{ service_name }}"
    enabled: true

- name: restart service
  when: service_restarted
  service:
    name: "{{ service_name }}"
    state: restarted
