matrix_synapse_domain: matrix.example.com
matrix_synapse_max_upload_size: 100M
matrix_synapse_enable_registration: false
matrix_synapse_registration_shared_secret: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters') }}"
